name: Release
on:
  push:
    branches:
      - main
  pull_request: # TODO: remove after testing
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  upload-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Create Baz binary
        run: |
          bun install
          
          # bun complains about it, but it is only imported dynamically for development
          mkdir -p node_modules/react-devtools-core
          echo "export default {};" > node_modules/react-devtools-core/index.js
          
          bun build --compile --outfile baz ./src/index.ts
      - name: Upload Baz binary
        uses: actions/upload-artifact@v4
        with:
          name: baz
          path: baz
          if-no-files-found: error
          retention-days: 30
          overwrite: true
